Repository notsoocool/codecache, pull requests merged in 2024-11, with the labels that each got.

#188 Add search through tags, language and categories.
  components/global/header.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#190 Customise the Side Scrollbar that matches with the theme | Issue #123
  app/styles/globals.css
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#195 CREATE DOCUMENTATION TEMPLATE
  .github/ISSUE_TEMPLATE/documentation.yml
Labels: gssoc-ext, hacktoberfest-accepted, level1

#202 Enhance BUG Report Template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#201 Create SECURITY.md
  SECURITY.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#203 Enhance the Feature Template
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, gssoc-ext, hacktoberfest-accepted, level1

#194 Update the Contributor fetch request
  app/(dashboard)/contributor/page.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2
