Repository notsoocool/codecache, pull requests merged in 2024-10, with the labels that each got.

#10 Develop: Adding the Drop Down Menu for the languages in the "Add Snippet" page
  .gitignore
  app/(dashboard)/addsnippets/page.tsx
  components/ui/select.tsx
  package-lock.json
Labels: gssoc-ext, hacktoberfest-accepted, level1

#15 added:: Meta Tags for SEO Improvement
  app/layout.tsx
Labels: gssoc-ext, hacktoberfest-accepted, level1

#28 fixes #26 snippet approve issue / required fields in payload
  app/api/request/accept/route.ts
Labels: bug, gssoc-ext, hacktoberfest-accepted, level1

#29 fix #27: migration to prisma orm and optimizations
  app/(dashboard)/addsnippets/page.tsx
  app/(dashboard)/layout.tsx
  app/(dashboard)/root/page.tsx
  app/(dashboard)/snippets/[id]/page.tsx
  app/(dashboard)/snippets/page.tsx
  app/api/bookmark/[id]/route.ts
  app/api/ratings/[snippetId]/route.ts
  app/api/ratings/route.ts
  app/api/request/accept/route.ts
  app/api/request/reject/route.ts
  app/api/request/route.ts
  app/api/snippets/[id]/route.ts
  app/api/snippets/route.ts
  app/layout.tsx
  bun.lockb
  lib/_db/connect.ts
  lib/_db/ratingModel.ts
  lib/_db/snippetModel.ts
  lib/_db/snippetRequestModel.ts
  lib/db.ts
  package.json
  prisma/schema.prisma
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#50 Fixes #16: Adds profile page
  app/(dashboard)/profile/page.tsx
  app/api/getCurrentUser/route.ts
  app/api/getUserProfile/[userId]/route.ts
  app/api/request/accept/route.ts
  app/layout.tsx
  bun.lockb
  components/global/header.tsx
  components/profile-tabs.tsx
  components/ui/avatar.tsx
  components/ui/tabs.tsx
  lib/db/snippetModel.ts
  lib/utils.ts
  package.json
  types.d.ts
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#52 Custom Dropdown for the profile page (section) with all the functionality #40
  bun.lockb
  components/global/ProfileDropdown.tsx
  components/global/header.tsx
  components/ui/avatar.tsx
  package.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#55 Improved the overview of the README
  .github/workflows/contributors.yml
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2

#66 Fixed "auto-label" GitHub workflow
  .github/workflows/auto-label.yml
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#72 Conditionall Render bookmarks Page
  components/global/navigation.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#71 My snippets tab done
  components/profile-tabs.tsx
  package-lock.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#37 Add Comments and Discussion Feature for Code Snippets #18
  app/(dashboard)/snippets/[id]/page.tsx
  app/api/request/accept/route.ts
  app/api/snippets/[id]/comments/route.ts
  bun.lockb
  lib/db/commentModel.ts
  lib/db/snippetModel.ts
  package-lock.json
  package.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#77 Delete Snippet Completed
  app/(dashboard)/profile/page.tsx
  app/(dashboard)/root/page.tsx
  app/api/getDeleteRequest/accept/route.ts
  app/api/getDeleteRequest/reject/route.ts
  app/api/getDeleteRequest/route.ts
  app/api/snippets/[id]/route.ts
  components/global/columns.tsx
  components/global/data-table.tsx
  components/profile-tabs.tsx
  components/ui/alert-dialog.tsx
  components/ui/table.tsx
  lib/db/deleteRequestModel.ts
  package-lock.json
  package.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#99 Readme update
  README.md
Labels: documentation, good first issue, gssoc-ext, hacktoberfest-accepted, level1

#96 Added the contributors page with sleek ui and dynamic functionality.
  app/(dashboard)/contributor/page.tsx
  bun.lockb
  components/global/ProfileDropdown.tsx
  components/global/header.tsx
  components/global/navigation.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#130 Added the husky
  .husky/pre-commit
  package.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#129 Rebuilt UI of home Page
  app/(dashboard)/page.tsx
  components/ui/accordion.tsx
  public/code.png
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#145 Added footer
  components/global/footer.tsx
  package.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#142 FAQ Section
  app/(dashboard)/faq/page.tsx
  components/global/navigation.tsx
  components/ui/faq.tsx
  public/faq.svg
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#161 Finally added quizzes
  app/(dashboard)/quiz/page.tsx
  components/ui/quiz.tsx
  public/q.png
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#162 Add feature: add contact-us page
  app/(dashboard)/contact/page.tsx
  components/global/navigation.tsx
  public/contact.svg
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#151 Develop
  .github/workflows/addcontributors
  README.md
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1

#181 add subscribe to the platform
  .env.example
  app/(dashboard)/contact/page.tsx
  app/api/subscribe/route.ts
  bun.lockb
  components/global/footer.tsx
  components/ui/stayupdated.tsx
  package.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level3

#166 Enhanced the logo of the website!
  public/logo-ashmita.png
Labels: gssoc-ext, hacktoberfest-accepted, level1

#152 added the docker-file
  .dockerignore
  Dockerfile
  README.md
  docker-compose.yml
  next.config.mjs
  package-lock.json
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#167 added multilanguage support
  app/layout.tsx
  app/styles/globals.css
  components/GTranslateLoader.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level2

#182 Ui: the FAQ section has some misalignments #178
  components/ui/accordion.tsx
Labels: enhancement, gssoc-ext, hacktoberfest-accepted, level1
